/*
 * tetris_stubs.c - Notify and event callback function stubs.
 * This file was generated by `gxv' from `tetris.G'.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/panel.h>
#include <xview/textsw.h>
#include <xview/xv_xrect.h>
#include "tetris_ui.h"
#include <group.h>


/*
 * Global object definitions.
 */
tetris_window_objects	*Tetris_window;
tetris_popup_objects	*Tetris_popup;

#ifdef MAIN

/*
 * Instance XV_KEY_DATA key.  An instance is a set of related
 * user interface objects.  A pointer to an object's instance
 * is stored under this key in every object.  This must be a
 * global variable.
 */
Attr_attribute	INSTANCE;

main(argc, argv)
	int	argc;
	char	**argv;
{
	/*
	 * Initialize XView.
	 */
	xv_init(XV_INIT_ARGC_PTR_ARGV, &argc, argv, NULL);
	INSTANCE = xv_unique_key();
	
	/*
	 * Initialize user interface components.
	 * Do NOT edit the object initializations by hand.
	 */
	Tetris_window = tetris_window_objects_initialize(NULL, NULL);
	Tetris_popup = tetris_popup_objects_initialize(NULL, Tetris_window->window);
	
	
	/*
	 * Turn control over to XView.
	 */
	xv_main_loop(Tetris_window->window);
	exit(0);
}

#endif


/*
 * Notify callback function for `start_button'.
 */
void
start_handler(item, event)
	Panel_item	item;
	Event		*event;
{
	tetris_window_objects *ip = (tetris_window_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("tetris: start_handler\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `help_button'.
 */
void
help_button_handler(item, event)
	Panel_item	item;
	Event		*event;
{
	tetris_window_objects *ip = (tetris_window_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("tetris: help_button_handler\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `size_setting'.
 */
void
size_notify(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	tetris_window_objects *ip = (tetris_window_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "tetris: size_notify: value: %u\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `color_setting'.
 */
void
color_notify(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	tetris_window_objects *ip = (tetris_window_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "tetris: color_notify: value: %u\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `level_setting'.
 */
void
level_notify(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	tetris_window_objects *ip = (tetris_window_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "tetris: level_notify: value: %u\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `height_setting'.
 */
void
height_notify(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	tetris_window_objects *ip = (tetris_window_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "tetris: height_notify: value: %u\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Event callback function for `canvas'.
 */
Notify_value
canvas_events(win, event, arg, type)
	Xv_window	win;
	Event		*event;
	Notify_arg	arg;
	Notify_event_type type;
{
	tetris_window_objects *ip = (tetris_window_objects *) xv_get(xv_get(win, CANVAS_PAINT_CANVAS_WINDOW), XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "tetris: canvas_events: event %d\n", event_id(event));
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return notify_next_event_func(win, (Notify_event) event, arg, type);
}

/*
 * Notify callback function for `type_setting'.
 */
void
type_notify(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	tetris_window_objects *ip = (tetris_window_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "tetris: type_notify: value: %u\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}
