/*
 * tetris_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `tetris.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include <gcm.h>
#include <group.h>
#include "tetris_ui.h"

/*
 * Initialize an instance of object `window'.
 */
tetris_window_objects *
tetris_window_objects_initialize(ip, owner)
	tetris_window_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (tetris_window_objects *) calloc(1, sizeof (tetris_window_objects))))
		return (tetris_window_objects *) NULL;
	if (!ip->window)
		ip->window = tetris_window_window_create(ip, owner);
	if (!ip->controls1)
		ip->controls1 = tetris_window_controls1_create(ip, ip->window);
	if (!ip->start_button)
		ip->start_button = tetris_window_start_button_create(ip, ip->controls1);
	if (!ip->type_setting)
		ip->type_setting = tetris_window_type_setting_create(ip, ip->controls1);
	if (!ip->size_setting)
		ip->size_setting = tetris_window_size_setting_create(ip, ip->controls1);
	if (!ip->color_setting)
		ip->color_setting = tetris_window_color_setting_create(ip, ip->controls1);
	if (!ip->help_button)
		ip->help_button = tetris_window_help_button_create(ip, ip->controls1);
	if (!ip->controls2)
		ip->controls2 = tetris_window_controls2_create(ip, ip->window);
	if (!ip->score_message)
		ip->score_message = tetris_window_score_message_create(ip, ip->controls2);
	if (!ip->score)
		ip->score = tetris_window_score_create(ip, ip->controls2);
	if (!ip->lines_message)
		ip->lines_message = tetris_window_lines_message_create(ip, ip->controls2);
	if (!ip->lines)
		ip->lines = tetris_window_lines_create(ip, ip->controls2);
	if (!ip->level_message)
		ip->level_message = tetris_window_level_message_create(ip, ip->controls2);
	if (!ip->level)
		ip->level = tetris_window_level_create(ip, ip->controls2);
	if (!ip->level_setting)
		ip->level_setting = tetris_window_level_setting_create(ip, ip->controls2);
	if (!ip->height_setting)
		ip->height_setting = tetris_window_height_setting_create(ip, ip->controls2);
	if (!ip->canvas)
		ip->canvas = tetris_window_canvas_create(ip, ip->window);
	return ip;
}

/*
 * Create object `window' in the specified instance.
 */
Xv_opaque
tetris_window_window_create(ip, owner)
	tetris_window_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	Xv_opaque		window_image;
	static unsigned short	window_bits[] = {
#include "../include/tetris.icon"
	};
	Xv_opaque		window_image_mask;
	static unsigned short	window_mask_bits[] = {
#include "../include/tetris.mask.icon"
	};
	
	window_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, window_bits,
		XV_WIDTH, 64,
		XV_HEIGHT, 64,
		NULL);
	window_image_mask = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, window_mask_bits,
		XV_WIDTH, 64,
		XV_HEIGHT, 64,
		NULL);
	obj = xv_create(owner, FRAME,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 281,
		XV_HEIGHT, 361,
		XV_LABEL, "BloX 1.0",
		FRAME_SHOW_FOOTER, TRUE,
		FRAME_SHOW_RESIZE_CORNER, FALSE,
		FRAME_ICON, xv_create(XV_NULL, ICON,
			ICON_IMAGE, window_image,
			ICON_MASK_IMAGE, window_image_mask,
			NULL),
		NULL);
	return obj;
}

/*
 * Create object `controls1' in the specified instance.
 */
Xv_opaque
tetris_window_controls1_create(ip, owner)
	tetris_window_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, 41,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `start_button' in the specified instance.
 */
Xv_opaque
tetris_window_start_button_create(ip, owner)
	tetris_window_objects	*ip;
	Xv_opaque	owner;
{
	extern void		start_handler();
	Xv_opaque	obj;
	Xv_opaque		start_button_image;
	static unsigned short	start_button_bits[] = {
#include "../include/start.button"
	};
	
	start_button_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, start_button_bits,
		XV_WIDTH, 16,
		XV_HEIGHT, 16,
		NULL);
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 8,
		PANEL_LABEL_WIDTH, 28,
		PANEL_LABEL_IMAGE, start_button_image,
		PANEL_NOTIFY_PROC, start_handler,
		NULL);
	return obj;
}

/*
 * Create object `type_setting' in the specified instance.
 */
Xv_opaque
tetris_window_type_setting_create(ip, owner)
	tetris_window_objects	*ip;
	Xv_opaque	owner;
{
	extern void		type_notify();
	Xv_opaque	obj;
	Xv_opaque		type_setting_image0;
	static unsigned short	type_setting_bits0[] = {
#include "../include/blox.button"
	};
	Xv_opaque		type_setting_image1;
	static unsigned short	type_setting_bits1[] = {
#include "../include/tetris.button"
	};
	
	type_setting_image0 = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, type_setting_bits0,
		XV_WIDTH, 16,
		XV_HEIGHT, 16,
		NULL);
	type_setting_image1 = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, type_setting_bits1,
		XV_WIDTH, 16,
		XV_HEIGHT, 16,
		NULL);
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 60,
		XV_Y, 8,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOOSE_NONE, FALSE,
		PANEL_NOTIFY_PROC, type_notify,
		PANEL_CHOICE_IMAGES,
			type_setting_image0,
			type_setting_image1,
			NULL,
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `size_setting' in the specified instance.
 */
Xv_opaque
tetris_window_size_setting_create(ip, owner)
	tetris_window_objects	*ip;
	Xv_opaque	owner;
{
	extern void		size_notify();
	Xv_opaque	obj;
	Xv_opaque		size_setting_image0;
	static unsigned short	size_setting_bits0[] = {
#include "../include/small.button"
	};
	Xv_opaque		size_setting_image1;
	static unsigned short	size_setting_bits1[] = {
#include "../include/big.button"
	};
	
	size_setting_image0 = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, size_setting_bits0,
		XV_WIDTH, 16,
		XV_HEIGHT, 16,
		NULL);
	size_setting_image1 = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, size_setting_bits1,
		XV_WIDTH, 16,
		XV_HEIGHT, 16,
		NULL);
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 116,
		XV_Y, 8,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOOSE_NONE, FALSE,
		PANEL_NOTIFY_PROC, size_notify,
		PANEL_CHOICE_IMAGES,
			size_setting_image0,
			size_setting_image1,
			NULL,
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `color_setting' in the specified instance.
 */
Xv_opaque
tetris_window_color_setting_create(ip, owner)
	tetris_window_objects	*ip;
	Xv_opaque	owner;
{
	extern void		color_notify();
	Xv_opaque	obj;
	Xv_opaque		color_setting_image0;
	static unsigned short	color_setting_bits0[] = {
#include "../include/color.button"
	};
	Xv_opaque		color_setting_image1;
	static unsigned short	color_setting_bits1[] = {
#include "../include/mono.button"
	};
	
	color_setting_image0 = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, color_setting_bits0,
		XV_WIDTH, 16,
		XV_HEIGHT, 16,
		NULL);
	color_setting_image1 = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, color_setting_bits1,
		XV_WIDTH, 16,
		XV_HEIGHT, 16,
		NULL);
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 172,
		XV_Y, 8,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOOSE_NONE, FALSE,
		PANEL_NOTIFY_PROC, color_notify,
		PANEL_CHOICE_IMAGES,
			color_setting_image0,
			color_setting_image1,
			NULL,
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `help_button' in the specified instance.
 */
Xv_opaque
tetris_window_help_button_create(ip, owner)
	tetris_window_objects	*ip;
	Xv_opaque	owner;
{
	extern void		help_button_handler();
	Xv_opaque	obj;
	Xv_opaque		help_button_image;
	static unsigned short	help_button_bits[] = {
#include "../include/help.button"
	};
	
	help_button_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, help_button_bits,
		XV_WIDTH, 16,
		XV_HEIGHT, 16,
		NULL);
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 236,
		XV_Y, 8,
		PANEL_LABEL_WIDTH, 28,
		PANEL_LABEL_IMAGE, help_button_image,
		PANEL_NOTIFY_PROC, help_button_handler,
		NULL);
	return obj;
}

/*
 * Create object `controls2' in the specified instance.
 */
Xv_opaque
tetris_window_controls2_create(ip, owner)
	tetris_window_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, (int)xv_get(ip->controls1, XV_Y) +
		      (int)xv_get(ip->controls1, XV_HEIGHT),
		XV_WIDTH, 121,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `score_message' in the specified instance.
 */
Xv_opaque
tetris_window_score_message_create(ip, owner)
	tetris_window_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 44,
		XV_Y, 4,
		PANEL_LABEL_STRING, "Score",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `score' in the specified instance.
 */
Xv_opaque
tetris_window_score_create(ip, owner)
	tetris_window_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 36,
		XV_Y, 20,
		PANEL_LABEL_STRING, "0000000",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `lines_message' in the specified instance.
 */
Xv_opaque
tetris_window_lines_message_create(ip, owner)
	tetris_window_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 44,
		XV_Y, 40,
		PANEL_LABEL_STRING, "Lines",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `lines' in the specified instance.
 */
Xv_opaque
tetris_window_lines_create(ip, owner)
	tetris_window_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 60,
		XV_Y, 56,
		PANEL_LABEL_STRING, "0",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `level_message' in the specified instance.
 */
Xv_opaque
tetris_window_level_message_create(ip, owner)
	tetris_window_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 44,
		XV_Y, 72,
		PANEL_LABEL_STRING, "Level",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `level' in the specified instance.
 */
Xv_opaque
tetris_window_level_create(ip, owner)
	tetris_window_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 60,
		XV_Y, 88,
		PANEL_LABEL_STRING, "0",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `level_setting' in the specified instance.
 */
Xv_opaque
tetris_window_level_setting_create(ip, owner)
	tetris_window_objects	*ip;
	Xv_opaque	owner;
{
	extern void		level_notify();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 24,
		XV_Y, 108,
		PANEL_CHOICE_NCOLS, 3,
		PANEL_LAYOUT, PANEL_VERTICAL,
		PANEL_CHOOSE_NONE, FALSE,
		PANEL_LABEL_STRING, "Level:",
		PANEL_NOTIFY_PROC, level_notify,
		PANEL_CHOICE_STRINGS,
			"1",
			"4",
			"7",
			"2",
			"5",
			"8",
			"3",
			"6",
			"9",
			NULL,
		PANEL_VALUE, 6,
		NULL);
	return obj;
}

/*
 * Create object `height_setting' in the specified instance.
 */
Xv_opaque
tetris_window_height_setting_create(ip, owner)
	tetris_window_objects	*ip;
	Xv_opaque	owner;
{
	extern void		height_notify();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 12,
		XV_Y, 200,
		PANEL_CHOICE_NCOLS, 3,
		PANEL_LAYOUT, PANEL_VERTICAL,
		PANEL_CHOOSE_NONE, FALSE,
		PANEL_LABEL_STRING, "Height:",
		PANEL_NOTIFY_PROC, height_notify,
		PANEL_CHOICE_STRINGS,
			" 0",
			" 3",
			" 6",
			" 9",
			" 1",
			" 4",
			" 7",
			"10",
			" 2",
			" 5",
			" 8",
			"11",
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `canvas' in the specified instance.
 */
Xv_opaque
tetris_window_canvas_create(ip, owner)
	tetris_window_objects	*ip;
	Xv_opaque	owner;
{
	extern Notify_value	canvas_events();
	Xv_opaque	obj;
	
	obj = xv_create(owner, CANVAS,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, (int)xv_get(ip->controls2, XV_X) +
		      (int)xv_get(ip->controls2, XV_WIDTH),
		XV_Y, (int)xv_get(ip->controls1, XV_Y) +
		      (int)xv_get(ip->controls1, XV_HEIGHT),
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		CANVAS_X_PAINT_WINDOW, TRUE,
		NULL);
	gcm_initialize_colors(obj, "Black", "Black");
	xv_set(canvas_paint_window(obj), WIN_CONSUME_EVENTS,
		WIN_MOUSE_BUTTONS,
		LOC_MOVE,
		LOC_DRAG,
		LOC_WINENTER,
		LOC_WINEXIT,
		WIN_ASCII_EVENTS,
		WIN_LEFT_KEYS,
		WIN_RIGHT_KEYS,
		WIN_TOP_KEYS,
		NULL, NULL);
	notify_interpose_event_func(canvas_paint_window(obj),
		(Notify_func) canvas_events, NOTIFY_SAFE);
	/*
	 * This line is here for backwards compatibility. It will be
	 * removed for the next release.
	 */
	xv_set(canvas_paint_window(obj), XV_KEY_DATA, INSTANCE, ip, NULL);
	return obj;
}

/*
 * Initialize an instance of object `popup'.
 */
tetris_popup_objects *
tetris_popup_objects_initialize(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (tetris_popup_objects *) calloc(1, sizeof (tetris_popup_objects))))
		return (tetris_popup_objects *) NULL;
	if (!ip->popup)
		ip->popup = tetris_popup_popup_create(ip, owner);
	if (!ip->controls3)
		ip->controls3 = tetris_popup_controls3_create(ip, ip->popup);
	if (!ip->message39)
		ip->message39 = tetris_popup_message39_create(ip, ip->controls3);
	if (!ip->message41)
		ip->message41 = tetris_popup_message41_create(ip, ip->controls3);
	if (!ip->group15)
		ip->group15 = tetris_popup_group15_create(ip, ip->controls3);
	if (!ip->message1)
		ip->message1 = tetris_popup_message1_create(ip, ip->controls3);
	if (!ip->message4)
		ip->message4 = tetris_popup_message4_create(ip, ip->controls3);
	if (!ip->message40)
		ip->message40 = tetris_popup_message40_create(ip, ip->controls3);
	if (!ip->message42)
		ip->message42 = tetris_popup_message42_create(ip, ip->controls3);
	if (!ip->message10)
		ip->message10 = tetris_popup_message10_create(ip, ip->controls3);
	if (!ip->message11)
		ip->message11 = tetris_popup_message11_create(ip, ip->controls3);
	if (!ip->message14)
		ip->message14 = tetris_popup_message14_create(ip, ip->controls3);
	if (!ip->message15)
		ip->message15 = tetris_popup_message15_create(ip, ip->controls3);
	if (!ip->message16)
		ip->message16 = tetris_popup_message16_create(ip, ip->controls3);
	if (!ip->message27)
		ip->message27 = tetris_popup_message27_create(ip, ip->controls3);
	if (!ip->message30)
		ip->message30 = tetris_popup_message30_create(ip, ip->controls3);
	if (!ip->message33)
		ip->message33 = tetris_popup_message33_create(ip, ip->controls3);
	if (!ip->message5)
		ip->message5 = tetris_popup_message5_create(ip, ip->controls3);
	if (!ip->message9)
		ip->message9 = tetris_popup_message9_create(ip, ip->controls3);
	if (!ip->message6)
		ip->message6 = tetris_popup_message6_create(ip, ip->controls3);
	if (!ip->message8)
		ip->message8 = tetris_popup_message8_create(ip, ip->controls3);
	if (!ip->message7)
		ip->message7 = tetris_popup_message7_create(ip, ip->controls3);
	if (!ip->group2)
		ip->group2 = tetris_popup_group2_create(ip, ip->controls3);
	if (!ip->message19)
		ip->message19 = tetris_popup_message19_create(ip, ip->controls3);
	if (!ip->message20)
		ip->message20 = tetris_popup_message20_create(ip, ip->controls3);
	if (!ip->message21)
		ip->message21 = tetris_popup_message21_create(ip, ip->controls3);
	if (!ip->message22)
		ip->message22 = tetris_popup_message22_create(ip, ip->controls3);
	if (!ip->message23)
		ip->message23 = tetris_popup_message23_create(ip, ip->controls3);
	if (!ip->message47)
		ip->message47 = tetris_popup_message47_create(ip, ip->controls3);
	if (!ip->message48)
		ip->message48 = tetris_popup_message48_create(ip, ip->controls3);
	if (!ip->group6)
		ip->group6 = tetris_popup_group6_create(ip, ip->controls3);
	if (!ip->message54)
		ip->message54 = tetris_popup_message54_create(ip, ip->controls3);
	if (!ip->group11)
		ip->group11 = tetris_popup_group11_create(ip, ip->controls3);
	if (!ip->message12)
		ip->message12 = tetris_popup_message12_create(ip, ip->controls3);
	if (!ip->message24)
		ip->message24 = tetris_popup_message24_create(ip, ip->controls3);
	if (!ip->message25)
		ip->message25 = tetris_popup_message25_create(ip, ip->controls3);
	if (!ip->group4)
		ip->group4 = tetris_popup_group4_create(ip, ip->controls3);
	if (!ip->message51)
		ip->message51 = tetris_popup_message51_create(ip, ip->controls3);
	if (!ip->group8)
		ip->group8 = tetris_popup_group8_create(ip, ip->controls3);
	if (!ip->message26)
		ip->message26 = tetris_popup_message26_create(ip, ip->controls3);
	if (!ip->message38)
		ip->message38 = tetris_popup_message38_create(ip, ip->controls3);
	if (!ip->message43)
		ip->message43 = tetris_popup_message43_create(ip, ip->controls3);
	if (!ip->group3)
		ip->group3 = tetris_popup_group3_create(ip, ip->controls3);
	if (!ip->message52)
		ip->message52 = tetris_popup_message52_create(ip, ip->controls3);
	if (!ip->group9)
		ip->group9 = tetris_popup_group9_create(ip, ip->controls3);
	if (!ip->message44)
		ip->message44 = tetris_popup_message44_create(ip, ip->controls3);
	if (!ip->message45)
		ip->message45 = tetris_popup_message45_create(ip, ip->controls3);
	if (!ip->message46)
		ip->message46 = tetris_popup_message46_create(ip, ip->controls3);
	if (!ip->group5)
		ip->group5 = tetris_popup_group5_create(ip, ip->controls3);
	if (!ip->message53)
		ip->message53 = tetris_popup_message53_create(ip, ip->controls3);
	if (!ip->group10)
		ip->group10 = tetris_popup_group10_create(ip, ip->controls3);
	if (!ip->message49)
		ip->message49 = tetris_popup_message49_create(ip, ip->controls3);
	if (!ip->message50)
		ip->message50 = tetris_popup_message50_create(ip, ip->controls3);
	if (!ip->group7)
		ip->group7 = tetris_popup_group7_create(ip, ip->controls3);
	if (!ip->message55)
		ip->message55 = tetris_popup_message55_create(ip, ip->controls3);
	if (!ip->group12)
		ip->group12 = tetris_popup_group12_create(ip, ip->controls3);
	if (!ip->message34)
		ip->message34 = tetris_popup_message34_create(ip, ip->controls3);
	if (!ip->message36)
		ip->message36 = tetris_popup_message36_create(ip, ip->controls3);
	if (!ip->group14)
		ip->group14 = tetris_popup_group14_create(ip, ip->controls3);
	if (!ip->message35)
		ip->message35 = tetris_popup_message35_create(ip, ip->controls3);
	if (!ip->message37)
		ip->message37 = tetris_popup_message37_create(ip, ip->controls3);
	if (!ip->group13)
		ip->group13 = tetris_popup_group13_create(ip, ip->controls3);
	if (!ip->message3)
		ip->message3 = tetris_popup_message3_create(ip, ip->controls3);
	if (!ip->message57)
		ip->message57 = tetris_popup_message57_create(ip, ip->controls3);
	if (!ip->message58)
		ip->message58 = tetris_popup_message58_create(ip, ip->controls3);
	if (!ip->message59)
		ip->message59 = tetris_popup_message59_create(ip, ip->controls3);
	if (!ip->message56)
		ip->message56 = tetris_popup_message56_create(ip, ip->controls3);
	if (!ip->message13)
		ip->message13 = tetris_popup_message13_create(ip, ip->controls3);
	if (!ip->message28)
		ip->message28 = tetris_popup_message28_create(ip, ip->controls3);
	if (!ip->message29)
		ip->message29 = tetris_popup_message29_create(ip, ip->controls3);
	if (!ip->message17)
		ip->message17 = tetris_popup_message17_create(ip, ip->controls3);
	if (!ip->group1)
		ip->group1 = tetris_popup_group1_create(ip, ip->controls3);
	if (!ip->message18)
		ip->message18 = tetris_popup_message18_create(ip, ip->controls3);
	if (!ip->message31)
		ip->message31 = tetris_popup_message31_create(ip, ip->controls3);
	if (!ip->message32)
		ip->message32 = tetris_popup_message32_create(ip, ip->controls3);
	if (!ip->message2)
		ip->message2 = tetris_popup_message2_create(ip, ip->controls3);
	if (!ip->group16)
		ip->group16 = tetris_popup_group16_create(ip, ip->controls3);
	if (!ip->message60)
		ip->message60 = tetris_popup_message60_create(ip, ip->controls3);
	window_fit(ip->controls3);
	
	window_fit(ip->popup);
	
	xv_set(ip->controls3,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		NULL);
	return ip;
}

/*
 * Create object `popup' in the specified instance.
 */
Xv_opaque
tetris_popup_popup_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 495,
		XV_HEIGHT, 770,
		XV_LABEL, "BloX: Help",
		XV_SHOW, FALSE,
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, FALSE,
		FRAME_CMD_PUSHPIN_IN, TRUE,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `controls3' in the specified instance.
 */
Xv_opaque
tetris_popup_controls3_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	gcm_initialize_colors(obj, NULL, NULL);
	return obj;
}

/*
 * Create object `message39' in the specified instance.
 */
Xv_opaque
tetris_popup_message39_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	Xv_opaque		message39_image;
	static unsigned short	message39_bits[] = {
#include "../include/vixen.shades.icon"
	};
	
	message39_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, message39_bits,
		XV_WIDTH, 64,
		XV_HEIGHT, 64,
		NULL);
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 429,
		XV_Y, 4,
		PANEL_ITEM_COLOR, gcm_color_index("BG3"),
		PANEL_LABEL_IMAGE, message39_image,
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `message41' in the specified instance.
 */
Xv_opaque
tetris_popup_message41_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	Xv_opaque		message41_image;
	static unsigned short	message41_bits[] = {
#include "../include/vixen.text.icon"
	};
	
	message41_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, message41_bits,
		XV_WIDTH, 64,
		XV_HEIGHT, 64,
		NULL);
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 428,
		XV_Y, 69,
		PANEL_ITEM_COLOR, gcm_color_index("Dim Gray"),
		PANEL_LABEL_IMAGE, message41_image,
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `group15' in the specified instance.
 */
Xv_opaque
tetris_popup_group15_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 428,
		XV_Y, 4,
		GROUP_TYPE, GROUP_NONE,
		GROUP_MEMBERS,
			ip->message39,
			ip->message41,
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `message1' in the specified instance.
 */
Xv_opaque
tetris_popup_message1_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 8,
		PANEL_LABEL_STRING, "BloX 1.0",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `message4' in the specified instance.
 */
Xv_opaque
tetris_popup_message4_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	Xv_opaque		message4_image;
	static unsigned short	message4_bits[] = {
#include "../include/tetris.icon"
	};
	
	message4_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, message4_bits,
		XV_WIDTH, 64,
		XV_HEIGHT, 64,
		NULL);
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 72,
		XV_Y, 8,
		PANEL_LABEL_IMAGE, message4_image,
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `message40' in the specified instance.
 */
Xv_opaque
tetris_popup_message40_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 192,
		XV_Y, 32,
		PANEL_LABEL_STRING, "\"All WORK and no PLAY",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `message42' in the specified instance.
 */
Xv_opaque
tetris_popup_message42_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 196,
		XV_Y, 48,
		PANEL_LABEL_STRING, "makes SPARC a dull toy!\"",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `message10' in the specified instance.
 */
Xv_opaque
tetris_popup_message10_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 96,
		PANEL_LABEL_STRING, "Game:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `message11' in the specified instance.
 */
Xv_opaque
tetris_popup_message11_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 76,
		XV_Y, 96,
		PANEL_LABEL_STRING, "Game is over when no more blocks can fall down the screen.",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `message14' in the specified instance.
 */
Xv_opaque
tetris_popup_message14_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 116,
		PANEL_LABEL_STRING, "Scoring:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `message15' in the specified instance.
 */
Xv_opaque
tetris_popup_message15_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 76,
		XV_Y, 116,
		PANEL_LABEL_STRING, "Object reaches bottom  = 32 points",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `message16' in the specified instance.
 */
Xv_opaque
tetris_popup_message16_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 76,
		XV_Y, 132,
		PANEL_LABEL_STRING, "First horizontal line      = 100 points  ",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `message27' in the specified instance.
 */
Xv_opaque
tetris_popup_message27_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 76,
		XV_Y, 148,
		PANEL_LABEL_STRING, "Second horizontal line  = 200 points  ",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `message30' in the specified instance.
 */
Xv_opaque
tetris_popup_message30_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 76,
		XV_Y, 164,
		PANEL_LABEL_STRING, "Third horizontal line     = 400 points  ",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `message33' in the specified instance.
 */
Xv_opaque
tetris_popup_message33_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 76,
		XV_Y, 180,
		PANEL_LABEL_STRING, "Fourth horizontal line   = 800 points  ",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `message5' in the specified instance.
 */
Xv_opaque
tetris_popup_message5_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 204,
		PANEL_LABEL_STRING, "Mouse Buttons:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `message9' in the specified instance.
 */
Xv_opaque
tetris_popup_message9_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	Xv_opaque		message9_image;
	static unsigned short	message9_bits[] = {
#include "../include/mouse.icon"
	};
	
	message9_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, message9_bits,
		XV_WIDTH, 64,
		XV_HEIGHT, 64,
		NULL);
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 172,
		XV_Y, 204,
		PANEL_LABEL_IMAGE, message9_image,
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `message6' in the specified instance.
 */
Xv_opaque
tetris_popup_message6_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 112,
		XV_Y, 224,
		PANEL_LABEL_STRING, "Move Left",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `message8' in the specified instance.
 */
Xv_opaque
tetris_popup_message8_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 240,
		XV_Y, 224,
		PANEL_LABEL_STRING, "Move Right",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `message7' in the specified instance.
 */
Xv_opaque
tetris_popup_message7_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 184,
		XV_Y, 268,
		PANEL_LABEL_STRING, "Rotate",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `group2' in the specified instance.
 */
Xv_opaque
tetris_popup_group2_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 112,
		XV_Y, 204,
		GROUP_TYPE, GROUP_NONE,
		GROUP_MEMBERS,
			ip->message9,
			ip->message6,
			ip->message8,
			ip->message7,
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `message19' in the specified instance.
 */
Xv_opaque
tetris_popup_message19_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 288,
		PANEL_LABEL_STRING, "Keyboard Commands:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `message20' in the specified instance.
 */
Xv_opaque
tetris_popup_message20_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 76,
		XV_Y, 304,
		PANEL_LABEL_STRING, "SPACE BAR = Accelerate block to bottom.",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `message21' in the specified instance.
 */
Xv_opaque
tetris_popup_message21_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 76,
		XV_Y, 320,
		PANEL_LABEL_STRING, "A or J  = Move Left.",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `message22' in the specified instance.
 */
Xv_opaque
tetris_popup_message22_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 76,
		XV_Y, 336,
		PANEL_LABEL_STRING, "S or K = Rotate Block.",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `message23' in the specified instance.
 */
Xv_opaque
tetris_popup_message23_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 76,
		XV_Y, 352,
		PANEL_LABEL_STRING, "D or L = Move Right.",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `message47' in the specified instance.
 */
Xv_opaque
tetris_popup_message47_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	Xv_opaque		message47_image;
	static unsigned short	message47_bits[] = {
#include "../include/start.button"
	};
	
	message47_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, message47_bits,
		XV_WIDTH, 16,
		XV_HEIGHT, 16,
		NULL);
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 20,
		XV_Y, 384,
		PANEL_LABEL_IMAGE, message47_image,
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `message48' in the specified instance.
 */
Xv_opaque
tetris_popup_message48_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 40,
		XV_Y, 387,
		PANEL_LABEL_STRING, ":",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `group6' in the specified instance.
 */
Xv_opaque
tetris_popup_group6_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 20,
		XV_Y, 384,
		GROUP_TYPE, GROUP_NONE,
		GROUP_MEMBERS,
			ip->message47,
			ip->message48,
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `message54' in the specified instance.
 */
Xv_opaque
tetris_popup_message54_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 76,
		XV_Y, 387,
		PANEL_LABEL_STRING, "Starts the game.",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `group11' in the specified instance.
 */
Xv_opaque
tetris_popup_group11_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 20,
		XV_Y, 384,
		GROUP_TYPE, GROUP_NONE,
		GROUP_MEMBERS,
			ip->group6,
			ip->message54,
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `message12' in the specified instance.
 */
Xv_opaque
tetris_popup_message12_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	Xv_opaque		message12_image;
	static unsigned short	message12_bits[] = {
#include "../include/blox.button"
	};
	
	message12_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, message12_bits,
		XV_WIDTH, 16,
		XV_HEIGHT, 16,
		NULL);
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 20,
		XV_Y, 404,
		PANEL_LABEL_IMAGE, message12_image,
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `message24' in the specified instance.
 */
Xv_opaque
tetris_popup_message24_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	Xv_opaque		message24_image;
	static unsigned short	message24_bits[] = {
#include "../include/tetris.button"
	};
	
	message24_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, message24_bits,
		XV_WIDTH, 16,
		XV_HEIGHT, 16,
		NULL);
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 40,
		XV_Y, 404,
		PANEL_LABEL_IMAGE, message24_image,
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `message25' in the specified instance.
 */
Xv_opaque
tetris_popup_message25_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 60,
		XV_Y, 407,
		PANEL_LABEL_STRING, ":",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `group4' in the specified instance.
 */
Xv_opaque
tetris_popup_group4_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 20,
		XV_Y, 404,
		GROUP_TYPE, GROUP_NONE,
		GROUP_MEMBERS,
			ip->message12,
			ip->message24,
			ip->message25,
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `message51' in the specified instance.
 */
Xv_opaque
tetris_popup_message51_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 76,
		XV_Y, 408,
		PANEL_LABEL_STRING, "Switches between BloX objects and Russian based objects.",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `group8' in the specified instance.
 */
Xv_opaque
tetris_popup_group8_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 20,
		XV_Y, 404,
		GROUP_TYPE, GROUP_NONE,
		GROUP_MEMBERS,
			ip->group4,
			ip->message51,
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `message26' in the specified instance.
 */
Xv_opaque
tetris_popup_message26_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	Xv_opaque		message26_image;
	static unsigned short	message26_bits[] = {
#include "../include/small.button"
	};
	
	message26_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, message26_bits,
		XV_WIDTH, 16,
		XV_HEIGHT, 16,
		NULL);
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 20,
		XV_Y, 425,
		PANEL_LABEL_IMAGE, message26_image,
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `message38' in the specified instance.
 */
Xv_opaque
tetris_popup_message38_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	Xv_opaque		message38_image;
	static unsigned short	message38_bits[] = {
#include "../include/big.button"
	};
	
	message38_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, message38_bits,
		XV_WIDTH, 16,
		XV_HEIGHT, 16,
		NULL);
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 40,
		XV_Y, 425,
		PANEL_LABEL_IMAGE, message38_image,
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `message43' in the specified instance.
 */
Xv_opaque
tetris_popup_message43_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 60,
		XV_Y, 428,
		PANEL_LABEL_STRING, ":",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `group3' in the specified instance.
 */
Xv_opaque
tetris_popup_group3_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 20,
		XV_Y, 425,
		GROUP_TYPE, GROUP_NONE,
		GROUP_MEMBERS,
			ip->message26,
			ip->message38,
			ip->message43,
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `message52' in the specified instance.
 */
Xv_opaque
tetris_popup_message52_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 76,
		XV_Y, 429,
		PANEL_LABEL_STRING, "Switches between little blocks and big blocks.",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `group9' in the specified instance.
 */
Xv_opaque
tetris_popup_group9_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 20,
		XV_Y, 425,
		GROUP_TYPE, GROUP_NONE,
		GROUP_MEMBERS,
			ip->group3,
			ip->message52,
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `message44' in the specified instance.
 */
Xv_opaque
tetris_popup_message44_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	Xv_opaque		message44_image;
	static unsigned short	message44_bits[] = {
#include "../include/color.button"
	};
	
	message44_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, message44_bits,
		XV_WIDTH, 16,
		XV_HEIGHT, 16,
		NULL);
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 20,
		XV_Y, 446,
		PANEL_LABEL_IMAGE, message44_image,
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `message45' in the specified instance.
 */
Xv_opaque
tetris_popup_message45_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	Xv_opaque		message45_image;
	static unsigned short	message45_bits[] = {
#include "../include/mono.button"
	};
	
	message45_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, message45_bits,
		XV_WIDTH, 16,
		XV_HEIGHT, 16,
		NULL);
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 40,
		XV_Y, 446,
		PANEL_LABEL_IMAGE, message45_image,
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `message46' in the specified instance.
 */
Xv_opaque
tetris_popup_message46_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 60,
		XV_Y, 449,
		PANEL_LABEL_STRING, ":",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `group5' in the specified instance.
 */
Xv_opaque
tetris_popup_group5_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 20,
		XV_Y, 446,
		GROUP_TYPE, GROUP_NONE,
		GROUP_MEMBERS,
			ip->message44,
			ip->message45,
			ip->message46,
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `message53' in the specified instance.
 */
Xv_opaque
tetris_popup_message53_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 76,
		XV_Y, 449,
		PANEL_LABEL_STRING, "Switches between color and monochrome.",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `group10' in the specified instance.
 */
Xv_opaque
tetris_popup_group10_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 20,
		XV_Y, 446,
		GROUP_TYPE, GROUP_NONE,
		GROUP_MEMBERS,
			ip->group5,
			ip->message53,
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `message49' in the specified instance.
 */
Xv_opaque
tetris_popup_message49_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	Xv_opaque		message49_image;
	static unsigned short	message49_bits[] = {
#include "../include/help.button"
	};
	
	message49_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, message49_bits,
		XV_WIDTH, 16,
		XV_HEIGHT, 16,
		NULL);
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 20,
		XV_Y, 466,
		PANEL_LABEL_IMAGE, message49_image,
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `message50' in the specified instance.
 */
Xv_opaque
tetris_popup_message50_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 40,
		XV_Y, 469,
		PANEL_LABEL_STRING, ":",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `group7' in the specified instance.
 */
Xv_opaque
tetris_popup_group7_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 20,
		XV_Y, 466,
		GROUP_TYPE, GROUP_NONE,
		GROUP_MEMBERS,
			ip->message49,
			ip->message50,
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `message55' in the specified instance.
 */
Xv_opaque
tetris_popup_message55_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 76,
		XV_Y, 469,
		PANEL_LABEL_STRING, "Brings up this help panel.",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `group12' in the specified instance.
 */
Xv_opaque
tetris_popup_group12_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 20,
		XV_Y, 466,
		GROUP_TYPE, GROUP_NONE,
		GROUP_MEMBERS,
			ip->group7,
			ip->message55,
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `message34' in the specified instance.
 */
Xv_opaque
tetris_popup_message34_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 20,
		XV_Y, 486,
		PANEL_LABEL_STRING, "Level:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `message36' in the specified instance.
 */
Xv_opaque
tetris_popup_message36_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 76,
		XV_Y, 486,
		PANEL_LABEL_STRING, "Level determines speed.  Level increases every 15 lines.",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `group14' in the specified instance.
 */
Xv_opaque
tetris_popup_group14_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 20,
		XV_Y, 486,
		GROUP_TYPE, GROUP_NONE,
		GROUP_MEMBERS,
			ip->message34,
			ip->message36,
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `message35' in the specified instance.
 */
Xv_opaque
tetris_popup_message35_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 20,
		XV_Y, 503,
		PANEL_LABEL_STRING, "Height:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `message37' in the specified instance.
 */
Xv_opaque
tetris_popup_message37_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 76,
		XV_Y, 503,
		PANEL_LABEL_STRING, "Height places obstacles on the field up to selected height.",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `group13' in the specified instance.
 */
Xv_opaque
tetris_popup_group13_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 20,
		XV_Y, 503,
		GROUP_TYPE, GROUP_NONE,
		GROUP_MEMBERS,
			ip->message35,
			ip->message37,
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `message3' in the specified instance.
 */
Xv_opaque
tetris_popup_message3_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 20,
		XV_Y, 528,
		PANEL_LABEL_STRING, "Command Line:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `message57' in the specified instance.
 */
Xv_opaque
tetris_popup_message57_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 76,
		XV_Y, 544,
		PANEL_LABEL_STRING, "-b =  Big blocks.",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `message58' in the specified instance.
 */
Xv_opaque
tetris_popup_message58_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 76,
		XV_Y, 561,
		PANEL_LABEL_STRING, "-m = Monochrome mode.",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `message59' in the specified instance.
 */
Xv_opaque
tetris_popup_message59_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 76,
		XV_Y, 578,
		PANEL_LABEL_STRING, "-t =  Russian objects.",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `message56' in the specified instance.
 */
Xv_opaque
tetris_popup_message56_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 76,
		XV_Y, 595,
		PANEL_LABEL_STRING, "-s =  Sun Logos in blocks.",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `message13' in the specified instance.
 */
Xv_opaque
tetris_popup_message13_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 32,
		XV_Y, 624,
		PANEL_LABEL_STRING, "Bugs & Upgrades:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `message28' in the specified instance.
 */
Xv_opaque
tetris_popup_message28_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 92,
		XV_Y, 640,
		PANEL_LABEL_STRING, "To register your copy and receive notices for upgrades and",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `message29' in the specified instance.
 */
Xv_opaque
tetris_popup_message29_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 92,
		XV_Y, 656,
		PANEL_LABEL_STRING, "new releases,",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `message17' in the specified instance.
 */
Xv_opaque
tetris_popup_message17_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 184,
		XV_Y, 656,
		PANEL_LABEL_STRING, "send $10 and the name of this program to: ",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `group1' in the specified instance.
 */
Xv_opaque
tetris_popup_group1_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 92,
		XV_Y, 656,
		GROUP_TYPE, GROUP_NONE,
		GROUP_MEMBERS,
			ip->message29,
			ip->message17,
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `message18' in the specified instance.
 */
Xv_opaque
tetris_popup_message18_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 160,
		XV_Y, 680,
		PANEL_ITEM_COLOR, gcm_color_index("Black"),
		PANEL_LABEL_STRING, "viXen Software",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `message31' in the specified instance.
 */
Xv_opaque
tetris_popup_message31_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 160,
		XV_Y, 696,
		PANEL_ITEM_COLOR, gcm_color_index("Black"),
		PANEL_LABEL_STRING, "P.O. Box 7974",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `message32' in the specified instance.
 */
Xv_opaque
tetris_popup_message32_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 160,
		XV_Y, 712,
		PANEL_ITEM_COLOR, gcm_color_index("Black"),
		PANEL_LABEL_STRING, "Fremont, CA 94537-7974",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `message2' in the specified instance.
 */
Xv_opaque
tetris_popup_message2_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 116,
		XV_Y, 736,
		PANEL_LABEL_STRING, "Copyright (c)1992 viXen Software",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `group16' in the specified instance.
 */
Xv_opaque
tetris_popup_group16_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 116,
		XV_Y, 736,
		GROUP_TYPE, GROUP_NONE,
		GROUP_MEMBERS,
			ip->message2,
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `message60' in the specified instance.
 */
Xv_opaque
tetris_popup_message60_create(ip, owner)
	tetris_popup_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 32,
		XV_Y, 756,
		PANEL_LABEL_STRING, "The Sun logo is a registered trademark of Sun Microsystems, Inc.",
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

